feat: direct connect associations and attachments
cloudquery/cq-provider-aws pull request #103
Opened 2021-06-16 20:44 UTC by James-Quigley

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/directconnect@v1.4.1/types#DirectConnectGatewayAssociation

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/directconnect@v1.4.1/types#DirectConnectGatewayAttachment

2021-06-18 07:28 UTC, roneli requested changes
Looks great, a few minor changes and remarks

2021-06-18 07:28 UTC, roneli commented on resources/directconnect_gateways.go
> +				Columns: []schema.Column{
I would also save the original DirectConnectGatewayId from AWS as resource_id (hopefully soon we will update the sdk to allow users to define any column as the PK)

2021-06-18 12:43 UTC, James-Quigley commented on resources/directconnect_gateways.go
> +					},
its deprecated. Should I still include it?

2021-06-19 15:42 UTC, roneli commented on resources/directconnect_gateways.go
> +					},
No need my bad

2021-06-19 15:43 UTC, roneli approved these changes
Looks good to me, generate the docs for the new tables (run docs.go inside docs directory) and we can merge

2021-06-21 13:23 UTC, James-Quigley commented
> Looks good to me, generate the docs for the new tables (run docs.go inside docs directory) and we can merge

2021-06-21 13:46 UTC, merged