feat: add image deprecation_time
cloudquery/cq-provider-aws pull request #1099
Opened 2022-06-23 21:04 UTC by nndegz

#### Summary

---

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [x] Run `go fmt` to format your code 🖊
- [x] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests. Learn more about testing [here](https://docs.cloudquery.io/docs/developers/sdk/testing) 🧪
- [x] Update the docs by running `go run ./docs/docs.go` and committing the changes 📃
- [ ] If adding a new resource, add [relevant Terraform files](../terraform) in a separate PR 📂
- [ ] Ensure the status checks below are successful ✅

2022-06-26 06:14 UTC, erezrokah commented
/test sha=1bc58ba8bab8c0b055ebfd4e7d289fbe7e9f16ec

2022-06-26 06:38 UTC, erezrokah commented
/test sha=9a48a7b7787465930a9f2454e51692bc0ed25228

2022-06-26 06:39 UTC, erezrokah requested changes, later dismissed
Thanks for the PR @nndegz 🚀  I added another commit to address the test failure, but will need your help to verify (see comment)

2022-06-26 06:39 UTC, erezrokah commented on resources/services/ec2/images_mock_test.go
> +	deprecationTime := "2050-11-05T08:15:30-05:00"
@nndegz can you confirm this is the expect format of `DeprecationTime`?

2022-06-27 18:10 UTC, bbernays approved these changes

2022-06-27 18:12 UTC, merged