feat: Added lightsail databases
cloudquery/cq-provider-aws pull request #1251
Opened 2022-07-20 11:45 UTC by amanenk

#### Summary

closes #773 

---

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [x] Run `go fmt` to format your code 🖊
- [x] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [x] Update or add tests. Learn more about testing [here](https://docs.cloudquery.io/docs/developers/sdk/testing) 🧪
- [x] Update the docs by running `go run ./docs/docs.go` and committing the changes 📃
- [x] If adding a new resource, add [relevant Terraform files](../terraform) in a separate PR 📂
- [x] Ensure the status checks below are successful ✅

2022-07-20 18:52 UTC, bbernays commented on resources/services/lightsail/databases.go
> +			},
Seems to be a duplicate of `region`

2022-07-22 08:32 UTC, irmatov requested changes

2022-07-22 08:32 UTC, irmatov commented on resources/services/lightsail/databases.go
> +	var sem = semaphore.NewWeighted(int64(MAX_GOROUTINES))
nit: new errgroup has SetLimit method which frees us from using semaphore and simplifies the code.

2022-07-22 08:32 UTC, irmatov commented on resources/services/lightsail/databases.go
> +			return diag.WrapError(err)
just `break` here, we'll get a proper error from `errs.Wait()`

2022-07-22 08:32 UTC, irmatov commented on resources/services/lightsail/databases.go
> +			return diag.WrapError(err)
^ this will be irrelevant if we use errgroup's `SetLimit`

2022-07-22 10:57 UTC, irmatov approved these changes

2022-07-22 10:57 UTC, merged