feat: Implement Glue Triggers resource
cloudquery/cq-provider-aws pull request #1322
Opened 2022-07-28 11:36 UTC by irmatov

2022-08-01 07:30 UTC, amanenk requested changes
Great job. Some description need to be fixed

2022-08-01 07:30 UTC, amanenk commented on resources/services/glue/triggers.go
> +				Description: "Number of events that must be received from Amazon EventBridge before EventBridge event trigger fires.  This member is required.",
remove this member is required

2022-08-01 07:30 UTC, amanenk commented on resources/services/glue/triggers.go
> +		result, err := svc.ListTriggers(ctx, &input)
`client.ListAndDetailResolver` can be used here.

2022-08-03 11:21 UTC, amanenk approved these changes

2022-08-03 12:26 UTC, hermanschaaf approved these changes

2022-08-03 12:34 UTC, merged