Iot resources
cloudquery/cq-provider-aws pull request #134
Opened 2021-08-05 07:29 UTC by fdistorted

2022-01-06 09:03 UTC, roneli requested changes
Looks good, a lot of resources added here, some resources re still missing such as authorizes, jobs etc' but we can add them in a future PR.  I noted in review but ill go back on it here in the API the default page != max allowed page so it important we always set to max to achieve highest performance.

2022-01-10 10:42 UTC, amanenk commented on resources/provider.go
> +			"iot.security_profiles":                 Wafv2WebAcls(),
It passed because we use IotSecurityProfiles() directly - not through Provider

2022-01-10 10:43 UTC, amanenk commented on resources/iot_things.go
> +func IotThings() *schema.Table {
> You can associate tags with thing groups, thing types, topic rules, jobs, security profiles, policies, and billing groups 
https://docs.aws.amazon.com/iot/latest/developerguide/tagging-iot.html

2022-01-17 14:38 UTC, roneli requested changes
Mostly descriptions and change to go 1.16 but looks good, would add e2e tests if possible

2022-01-17 14:38 UTC, roneli commented on resources/services/iot/iot_ca_certificates.go
> +			},
missing description

2022-01-17 14:38 UTC, roneli commented on resources/services/iot/iot_security_profiles.go
> +			},
missing description

2022-01-17 14:38 UTC, roneli commented on resources/services/iot/iot_thing_groups.go
> +			},
missing description

2022-01-17 14:38 UTC, roneli commented on resources/services/iot/iot_things.go
> +			},
missing description

2022-01-17 16:26 UTC, roneli approved these changes
LGTM

2022-01-17 16:26 UTC, merged