feat: Added glue table partitions and indexes
cloudquery/cq-provider-aws pull request #1377
Opened 2022-08-03 06:46 UTC by amanenk

#### Summary

closes #1368 
closes #1366 

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests. Learn more about testing [here](https://docs.cloudquery.io/docs/developers/sdk/testing) 🧪
- [ ] Update the docs by running `go run ./docs/docs.go` and committing the changes 📃
- [ ] If adding a new resource, add [relevant Terraform files](../terraform) in a separate PR 📂
- [ ] Ensure the status checks below are successful ✅

2022-08-03 10:38 UTC, disq commented
Maybe add a unit test just for the resolver? The documentation (godoc) for the method needs more clarification or examples as well.

2022-08-04 14:15 UTC, candiduslynx requested changes

2022-08-04 14:15 UTC, candiduslynx commented on docs/tables/aws_glue_database_table_partitions.md
> +|storage_descriptor_additional_locations|text[]|A list of locations that point to the path where a Delta table is located|
`storage_descriptor_` prefix seems too much

2022-08-04 14:15 UTC, candiduslynx commented on docs/tables/aws_glue_database_table_partitions.md
> +|storage_descriptor_schema_reference_schema_id_registry_name|text|The name of the schema registry that contains the schema|
`storage_descriptor_schema_reference_schema_id` -> json column?

2022-08-04 14:15 UTC, candiduslynx commented on docs/tables/aws_glue_database_table_partitions.md
> +|storage_descriptor_serde_info_name|text|Name of the SerDe|
`storage_descriptor_serde_info` -> json column?

2022-08-05 11:47 UTC, bbernays commented
I like the resolver you added in this PR... My question looking at these fields is whether this is going to fetch too much data... as all of the nested calls are going to happen sequentially.... And looking at the Index/Partition data it doesn't seem that compliance/ security focused...

2022-08-09 08:46 UTC, amanenk commented
> I like the resolver you added in this PR... My question looking at these fields is whether this is going to fetch too much data... as all of the nested calls are going to happen sequentially.... And looking at the Index/Partition data it doesn't seem that compliance/ security focused...

Agree on partitions. I have removed them. I have left indexes because it is infrastructural data that does not depend on data that is "fed" to glue

2022-08-10 10:08 UTC, candiduslynx approved these changes

2022-08-10 10:41 UTC, yevgenypats approved these changes

2022-08-10 12:26 UTC, bbernays approved these changes

2022-08-11 08:18 UTC, merged