cloudfront distributions regenerated and tags added
cloudquery/cq-provider-aws pull request #207
Opened 2021-10-07 09:01 UTC by amanenk

2021-11-30 21:02 UTC, bbernays approved these changes
Overall it looks good, but are we not grabbing any data from `GetDistribution` as not all information is available from `ListDistributions`

See this issue: #305

2021-12-01 10:59 UTC, amanenk commented on resources/cloudfront_distributions.go
> +	}
Could you explain more?

2021-12-01 10:59 UTC, amanenk commented
I have regenerated with GetDistribution result

2021-12-01 13:19 UTC, bbernays commented on resources/cloudfront_distributions.go
> +	}
From the docs this field seems to be solely about chinese regulations that might not be relevant to other regions

`AWS services in China customers must file for an Internet Content Provider (ICP) recordal if they want to serve content publicly on an alternate domain name, also known as a CNAME, that they've added to CloudFront`

2021-12-01 18:25 UTC, bbernays approved these changes
LGTM

2021-12-02 09:27 UTC, roneli requested changes
Required to drop tables that turned into jsons.

2021-12-02 09:27 UTC, roneli commented on resources/cloudfront_distributions.go
> +				Name:        "ip_v6_enabled",
ip_v6 -> ipv6

2021-12-02 13:13 UTC, spangenberg approved these changes
LGTM

2021-12-02 19:41 UTC, roneli approved these changes

2021-12-03 10:16 UTC, merged