Fetch IAM User data from ListUsers and CredentialReport
cloudquery/cq-provider-aws pull request #21
Opened 2021-03-24 18:52 UTC by James-Quigley

Fixes #20.

Gets a list of users from ListUsers as well as a credential report and merges the data, ignoring any unused data from the credential report

2021-03-25 10:18 UTC, yevgenypats requested changes
Thanks! One comment.

2021-03-25 10:18 UTC, yevgenypats commented on resources/iam/users.go
> +		if user.Arn == &reportUser.ARN {
Strange that it worked because looks like you are comparing pointers. It should be the other way around. `*user.Arn == reportUser.ARN`

2021-03-30 14:48 UTC, James-Quigley commented
I think this should be good to go @yevgenypats

2021-03-30 14:55 UTC, yevgenypats commented
@James-Quigley merging! for some reason didn't get the notification of the additional commit.

2021-03-30 14:55 UTC, merged