Add RDS Cluster and DB snapshots and attributes
cloudquery/cq-provider-aws pull request #287
Opened 2021-11-23 11:06 UTC by irmatov

2021-11-23 12:03 UTC, roneli requested changes
Looks good, 1 change required, and e2e tests.

2021-11-23 14:17 UTC, irmatov commented on resources/rds_db_snapshots.go
> +				Name:        "aws_rds_db_snapshot_processor_features",
converted to json field

2021-11-23 15:47 UTC, roneli approved these changes
LGTM, add e2e tests and we can merge

2021-11-24 10:30 UTC, irmatov commented
e2e tests added

2021-11-24 13:38 UTC, merged