Enhance config configuratiguration recorder with status
cloudquery/cq-provider-aws pull request #301
Opened 2021-11-25 08:43 UTC by spangenberg

Enhance for https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-pci-controls.html#pcidss-config-1

2021-11-25 09:06 UTC, roneli requested changes
LGTM, would move the tests to a separate file, see comment in review.

2021-11-25 09:06 UTC, roneli commented on client/mocks/builders_test.go
> +func buildConfigConfigurationRecordersMock(t *testing.T, ctrl *gomock.Controller) client.Services {
I would move this to a new file, this is legacy testing code and we should slowly remove from it and depercate.

2021-11-26 15:36 UTC, bbernays commented on resources/config_configuration_recorders.go
> +		res <- configurationRecorderWrapper{
Can we add an `exists` type field? That way we can have positive confirmation of the record in the database compared to having to handle if the record is missing for whatever reason (not in config, permissions issue, etc)

2021-11-29 13:29 UTC, roneli approved these changes
LGTM, can merge after fixing @bbernays suggestion

2021-11-30 08:44 UTC, merged