Add RDS event subscriptions
cloudquery/cq-provider-aws pull request #322
Opened 2021-12-02 13:05 UTC by irmatov

2021-12-02 13:53 UTC, roneli requested changes
Missing PK, we should also want to add some e2e testing for this resource

2021-12-02 13:53 UTC, roneli commented on resources/rds_event_subscriptions.go
> +		Columns: []schema.Column{
missing PK

2021-12-02 13:56 UTC, amanenk approved these changes
Looks good.

2021-12-03 08:09 UTC, irmatov commented
e2e test added

2021-12-03 09:30 UTC, roneli approved these changes
LGTM

2021-12-03 09:36 UTC, merged