Add Contributing.md
cloudquery/cq-provider-aws pull request #335
Opened 2021-12-06 18:53 UTC by bbernays

2021-12-06 18:58 UTC, disq commented on CONTRIBUTING.md
> +![architecure overview](https://docs.cloudquery.io/assets/images/cloudquery-architecture-02b1d1162883cd02510db2cb75c29d27.png)
```suggestion
![architecture overview](https://docs.cloudquery.io/assets/images/cloudquery-architecture-02b1d1162883cd02510db2cb75c29d27.png)
```

2021-12-06 19:00 UTC, ukmadlz reviewed
I feel that we should have local build instructions as part of this? (requirements etc)

2021-12-07 18:41 UTC, bbernays commented
Once this PR is approved and merged, I will copy the `Contributors.md` file to the other repos

2021-12-07 20:37 UTC, yevgenypats commented
Suggesting the following structure:
```
docs/contribution
        README.md
        moving this file: https://github.com/cloudquery/cq-provider-aws/blob/main/adding_a_new_resource.md to docs/contribution as well and linking to it from the README.md
```

2021-12-07 20:38 UTC, yevgenypats requested changes
Suggested a bit different structure and also link to adding a new resource which is the specific guidelines.

2021-12-07 20:53 UTC, yevgenypats commented
updated my suggestion to adhere to GitHub auto-detect contribution files - https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

2021-12-08 13:15 UTC, amanenk requested changes
Great job. The description clear and structured. I found a few minor issues with links.

2021-12-08 13:15 UTC, amanenk commented on CONTRIBUTING.md
> +  * [SDK](#provider-sdk)
this and link below does not work.

2021-12-08 13:15 UTC, amanenk commented on CONTRIBUTING.md
> +[I don't want to read this whole thing, I just have a question!!!](#i-dont-want-to-read-this-whole-thing-i-just-have-a-question)
This link does not work

2021-12-08 13:15 UTC, amanenk commented on CONTRIBUTING.md
> +  * [Pull Requests](#pull-requests)
this link does not work

2021-12-08 15:04 UTC, bbernays commented on CONTRIBUTING.md
> +[I don't want to read this whole thing, I just have a question!!!](#i-dont-want-to-read-this-whole-thing-i-just-have-a-question)
thank you. fixed

2021-12-08 15:34 UTC, bbernays commented on CONTRIBUTING.md
> +  * [SDK](#provider-sdk)
fixed

2021-12-10 13:35 UTC, spangenberg approved these changes
LGTM
No further remarks with all the additions.

2021-12-10 14:12 UTC, disq approved these changes

2021-12-10 14:58 UTC, merged