Cloudfront implementation
cloudquery/cq-provider-aws pull request #40
Opened 2021-04-25 09:37 UTC by fdistorted

Please look at my cloudfront implementation.
I think I have understood the structure of a code.
I didn't do any tests yet (I need to spend some more time t learn how to do it)

2021-04-25 10:18 UTC, yevgenypats commented
@fdistorted This looks great! There are a few minor bugs and tests missing but no need to do this now. I've updated Olga and we can proceed! Looking forward!

2021-05-04 12:07 UTC, roneli commented
Adds cloudfront distributions https://github.com/cloudquery/cq-provider-aws/issues/4

2021-05-05 06:59 UTC, roneli requested changes

2021-05-05 06:59 UTC, roneli commented on client/mocks/builders_test.go
> +	}
you can do this in one line i.e if err := faker.FakeData(&ds); err != nil { return t.Fatal(err) }

2021-05-05 06:59 UTC, roneli commented on resources/cloudfront_distributions.go
> +				Name:     "viewer_certificate_certificate",
viewer_certificate_certificate -> viewer_certificate

2021-05-05 06:59 UTC, roneli commented on resources/cloudfront_distributions.go
> +				Name:     "viewer_certificate_certificate_source",
viewer_certificate_certificate_source ->  viewer_certificate_source

2021-05-05 06:59 UTC, roneli commented on resources/cloudfront_distributions.go
> +				Name:     "default_cache_behaviour_lambda_function_associations", //todo check if this kind of relation is correct
remove todo, and  I would do cache_behaviour  instead of default_cache_behaviour as changed above with the fields

2021-05-05 06:59 UTC, roneli commented on resources/cloudfront_distributions.go
> +						Resolver: schema.PathResolver("CustomOriginConfig.OriginSslProtocols.Items"),
custom_origin_config_origin -> custom_origin_config

2021-05-05 06:59 UTC, roneli commented on resources/cloudfront_distributions.go
> +	if r.Members != nil {
invert this clause

2021-05-05 06:59 UTC, roneli commented on resources/cloudfront_distributions.go
> +	if r.FailoverCriteria != nil && r.FailoverCriteria.StatusCodes != nil {
invert this clause

2021-05-05 10:19 UTC, roneli approved these changes

2021-05-05 10:21 UTC, merged