feat: Added generic api error ignore routine
cloudquery/cq-provider-aws pull request #448
Opened 2022-01-28 09:55 UTC by amanenk

Most of the errors that should be ignored has a few common prefixes/suffixes. The function checks if error should be ignored and if it is it logs error as warning and allows to skip it. The function is used only in a few places. After PR approve I will propagate it to other resources.

2022-01-31 16:37 UTC, disq commented
also: https://github.com/cloudquery/cq-provider-aws/pull/462

2022-02-02 08:54 UTC, roneli requested changes
Good helper method, had some comments

2022-02-02 08:54 UTC, roneli commented on client/helpers.go
> +}
use the funk library instead you can use funk.Contains

2022-02-02 08:54 UTC, roneli commented on client/helpers.go
> +func (c *Client) IgnoreApiError(err error) bool {
the naming is wrong, its a IsNotFoundError

2022-02-02 08:54 UTC, roneli commented on client/helpers.go
> +			strings.HasSuffix(errorCode, "NotFoundError") {
we could use contains here no? or a regex?

2022-02-02 08:54 UTC, roneli commented on client/helpers.go
> +		if stringOneOf(errorCode, "ResourceNotFoundException", "WAFNonexistentItemException") ||
would make this error codes a const of strings as it might grow larger overtime.

2022-02-04 17:43 UTC, disq approved these changes

2022-02-04 17:51 UTC, roneli approved these changes
LGTM, had one nit.

2022-02-04 17:51 UTC, roneli commented on client/helpers.go
> +	return false
Nit:
```suggestion
	if !errors.As(err, &ae) {
	   return false
	}
        errorCode := ae.ErrorCode()
        for _, s := range notFoundErrorPrefixes {
	        if strings.Contains(errorCode, s) {
		        c.logger.Warn("API returned \"NotFound\" error ignoring it...", "error", err)
		        return true
	        }
        }
        return false
```

2022-02-07 10:40 UTC, roneli approved these changes
LGTM

2022-02-07 10:42 UTC, merged