feat: Added access analyzer archive rules
cloudquery/cq-provider-aws pull request #564
Opened 2022-03-14 15:57 UTC by amanenk

closes #495

2022-03-14 18:50 UTC, bbernays commented on resources/services/accessanalyzer/analyzers.go
> +				Description: "The status of the analyzer. The status of the analyzer. An Active analyzer successfully monitors supported resources and generates new findings. The analyzer is Disabled when a user
`The status of the analyzer. The status of the analyzer` duplicated

2022-03-16 10:45 UTC, bbernays commented on resources/provider/migrations/timescale/21_v0.10.12.up.sql
> +    ADD CONSTRAINT aws_ec2_eips_pk PRIMARY KEY (cq_fetch_date, account_id, allocation_id);
I think the migrations should now be `22_v0.10.13`

2022-03-16 13:18 UTC, roneli commented on resources/services/accessanalyzer/analyzers.go
> +				}
There was an issue with access analyzer in AWS SDK it was missing a middleware, so I manually added it. Might have been fixed, we need to update the service and check

2022-03-16 13:34 UTC, bbernays commented on resources/services/accessanalyzer/analyzers.go
> +				}
We should document that issue so we can track it and remove this code when it is no longer needed

2022-03-16 14:50 UTC, bbernays approved these changes

2022-03-19 23:16 UTC, yevgenypats requested changes
Looks good. One comment + rebase needed.

2022-03-19 23:16 UTC, yevgenypats commented on resources/services/accessanalyzer/analyzers.go
> +			return err
Missing diag.WrapError

2022-03-19 23:17 UTC, yevgenypats commented on resources/services/accessanalyzer/analyzers.go
>  			return err
Add diag.WrapError

2022-03-20 19:28 UTC, yevgenypats approved these changes

2022-03-20 19:29 UTC, merged