feat: Add EC2 Instance Statuses
cloudquery/cq-provider-aws pull request #566
Opened 2022-03-14 20:18 UTC by dakotalillie

I'm submitting this PR on behalf on @mlozoya2, who has not yet been authorized to submit PRs to CloudQuery himself.

2022-03-15 17:54 UTC, bbernays reviewed
Thank you very much for this PR! A few small comments, but overall looks great!!

2022-03-15 17:54 UTC, bbernays commented on resources/services/ec2/instance_statuses.go
> +			{
I would add an `arn` column just like in the `aws_ec2_instances`

2022-03-15 17:54 UTC, bbernays commented on resources/services/ec2/instance_statuses.go
> +		Resolver:     fetchEc2InstanceStatuses,
You should have a PK on each table. For this table you can use the ARN field (see comment below)

2022-03-15 17:54 UTC, bbernays commented on resources/services/ec2/instance_statuses.go
> +				Name:        "instance_status_details",
I would remove the `instance_status_` prefix from column names

2022-03-15 17:54 UTC, bbernays commented on resources/services/ec2/instance_statuses.go
> +	r := parent.Item.(types.InstanceStatus)
I would check the casting was successful:

```suggestion
	r, ok := parent.Item.(types.InstanceStatus)
	if !ok {
		return fmt.Errorf("not ec2 instance status")
	}
	
```

2022-03-15 17:54 UTC, bbernays commented on resources/services/ec2/instance_statuses.go
> +				Name:        "system_status_status",
```suggestion
				Name:        "system_status",
```

2022-03-16 18:05 UTC, mlozoya2 commented
@bbernays Thanks for the review! We pushed some changes to address your comments. Let me know if there is anything else we need for this.

2022-03-17 08:45 UTC, roneli approved these changes
LGTM

2022-03-17 12:00 UTC, bbernays requested changes

2022-03-17 12:00 UTC, bbernays commented on resources/services/ec2/instance_statuses.go
> +					return []string{"instance-status", *resource.Item.(types.InstanceStatus).InstanceId}, nil
i think the resource should be just `instance` rather than `instance-status`

2022-03-17 12:19 UTC, bbernays approved these changes

2022-03-17 12:19 UTC, merged