fix: Handle `GetModelTemplate` errors
cloudquery/cq-provider-aws pull request #567
Opened 2022-03-15 12:23 UTC by zagronitay

2022-03-15 15:15 UTC, bbernays commented on resources/services/apigateway/rest_apis.go
> +		case "NotFoundException":
I think ontop of `NotFoundException` we should also handle the `BadRequestException`. That way customers that are looking for Models that have issues can just search for 
``` sql
select * from aws_apigateway_rest_api_models where model_template is nil
```

2022-03-15 16:08 UTC, disq commented on resources/services/apigateway/rest_apis.go
> +		case "NotFoundException":
@bbernays good idea, but this would also mask any potential issues in the code no?

2022-03-15 16:51 UTC, disq commented on resources/services/apigateway/rest_apis.go
> +	if client.IsNotFoundError(err) {
This will panic in `errors.As` inside the fn, move the check inside `if err != nil` :)

2022-03-16 10:43 UTC, disq commented
What's the verdict on `BadRequestException` handling?

2022-03-16 10:53 UTC, bbernays commented
> What's the verdict on `BadRequestException` handling?

I would be alright settling for just a warning

2022-03-17 17:10 UTC, disq commented
> I would be alright settling for just a warning

So returning a diag with `diag.NewBaseError` in case of `BadRequestException` should work @zagronitay

2022-03-18 09:13 UTC, disq requested changes

2022-03-18 09:13 UTC, disq commented on resources/services/apigateway/rest_apis.go
> +			return diag.NewBaseError(err, diag.RESOLVING, diag.WithType(diag.RESOLVING), client.ParseSummaryMessage(err))
```suggestion
			return diag.NewBaseError(err, diag.RESOLVING, diag.WithSeverity(diag.WARNING), client.ParseSummaryMessage(err))
```

2022-03-19 20:03 UTC, yevgenypats requested changes

2022-03-19 20:03 UTC, yevgenypats commented on resources/services/apigateway/rest_apis.go
> +		errorCode := ae.ErrorCode()
Good that we have integration test :) This code panics as it just accessing nil. 

https://github.com/cloudquery/cq-provider-aws/runs/5598183118?check_suite_focus=true#step:8:2133

2022-03-19 23:07 UTC, yevgenypats commented
Fixed in https://github.com/cloudquery/cq-provider-aws/pull/591

2022-03-19 23:07 UTC, closed without merging