vpc endpoints implementation
cloudquery/cq-provider-aws pull request #59
Opened 2021-05-05 13:29 UTC by fdistorted

2021-05-05 14:37 UTC, roneli requested changes

2021-05-05 14:37 UTC, roneli commented on resources/ec2_vpc_endpoints.go
> +	svc := meta.(*client.Client).Services().EC2
I think he first line is redundant

2021-05-05 15:00 UTC, James-Quigley requested changes

2021-05-05 16:10 UTC, James-Quigley approved these changes

2021-05-06 07:11 UTC, roneli approved these changes

2021-05-06 07:11 UTC, roneli commented
Looks great, fix conflicts and we can merge.

2021-05-06 08:36 UTC, merged