Elbv1
cloudquery/cq-provider-aws pull request #63
Opened 2021-05-13 13:54 UTC by fdistorted

elbv1 implementation

2021-05-13 15:19 UTC, fdistorted commented
I have used  custom type and loaded attributes on fetch phase. Then each attributes field was resolved separately. Attributes could be set in post resolver. I is simpler to read because all fields names are set automatically and structure is preserved.

2021-05-13 17:26 UTC, roneli requested changes

2021-05-13 17:26 UTC, roneli commented on resources/elbv1_load_balancers.go
> +			if (i+1)%20 == 0 || i+1 == cap(loadBalancerWrappers) {
See my comment in route53 PR #60

2021-05-13 17:26 UTC, roneli commented on resources/elbv1_load_balancers.go
> +		return errors.New("not load balancer")
I saw you defined an error in #60 would we just use it for all errors ?

2021-05-16 07:24 UTC, roneli requested changes
Looks great, 1 minor suggestion left and issue with chunk size increase

2021-05-16 07:24 UTC, roneli commented on resources/elbv1_load_balancers.go
> +			end := i + 20
+10 or+ 20 which is correct? better to use a const type for this number.

2021-05-16 07:24 UTC, roneli commented on resources/elbv1_load_balancers.go
> +	processLoadBalancers := func(loadBalancers []types.LoadBalancerDescription) error {
why not move this into a function under elbv1_types and pass the svc + load balancers?

2021-05-18 09:53 UTC, roneli approved these changes

2021-05-18 09:53 UTC, merged