chore: Add TF for wafv2 ipsets and regex sets
cloudquery/cq-provider-aws pull request #676
Opened 2022-04-08 12:59 UTC by irmatov

2022-04-11 08:56 UTC, roneli commented on terraform/wafv2/prod/terraform.tf
> +#  backend "s3" {
why is this commented out?

2022-04-11 09:05 UTC, irmatov commented on terraform/wafv2/prod/terraform.tf
> +#  backend "s3" {
my bad. fixed.

2022-04-12 09:22 UTC, spangenberg approved these changes
LGTM

2022-04-12 09:50 UTC, bbernays requested changes

2022-04-12 10:06 UTC, irmatov commented on terraform/wafv2/prod/terraform.tf
> +    key            = "backup"
:facepalm: Fixed, thanks!

2022-04-12 10:09 UTC, bbernays approved these changes

2022-04-12 10:17 UTC, merged