Feat/ec2 host
cloudquery/cq-provider-aws pull request #697
Opened 2022-04-13 16:06 UTC by zagronitay

2022-04-13 16:57 UTC, disq approved these changes

2022-04-18 09:05 UTC, disq commented
I approved before the migrations? 😮

2022-04-18 10:56 UTC, disq requested changes

2022-04-18 10:56 UTC, disq commented on resources/services/ec2/hosts.go
> +				Name:        "aws_ec2_host_available_capacity_available_instance_capacity",
Maybe just `aws_ec2_host_available_instance_capacity`?

2022-04-18 14:36 UTC, disq approved these changes

2022-04-18 14:48 UTC, roneli reviewed
LGTM, had one naming nit, maybe convert available capacity to a json~ not sure tbh there

2022-04-18 14:48 UTC, roneli commented on docs/tables/aws_ec2_hosts.md
> +|available_capacity_available_vcpus|integer|The number of vCPUs available for launching instances onto the Dedicated Host.|
available_vcpus

2022-04-18 14:48 UTC, roneli commented on docs/tables/aws_ec2_host_available_instance_capacity.md
> +# Table: aws_ec2_host_available_instance_capacity
maybe a json array?

2022-04-18 16:19 UTC, roneli approved these changes

2022-04-18 16:20 UTC, merged