Fixed Quota error by multiplying services per account and region.
cloudquery/cq-provider-aws pull request #70
Opened 2021-05-19 10:49 UTC by zagronitay

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/throttling.html

https://github.com/cloudquery/cloudquery/issues/94

2021-05-19 11:08 UTC, roneli commented on client/client.go
> +func (s *ServicesManager) ServiceByAccountAndRegion(accountId string, region string) *Services {
Services*ByAccountAndRegion

2021-05-19 11:09 UTC, roneli approved these changes
Looks good, minor suggestions (grammar + const)

2021-05-19 11:09 UTC, roneli commented on client/client.go
> +var defaultRegion = "us-east-1"
const

2021-05-19 20:15 UTC, yevgenypats requested changes
I've tested it and Im not sure it solved the problem. The AWS client should be goroutine safe per documentation also the retrier is automatically copied like all other options on each call. For example see this : https://github.com/aws/aws-sdk-go-v2/blob/main/service/autoscaling/api_client.go#L121 

I suspect this is something else like incorrect retrier configuration in the first place. I've a few ideas but let's discuss this live tomorrow

@roneli @zagronitay

2021-05-20 12:08 UTC, yevgenypats approved these changes

2021-05-20 14:40 UTC, merged