feat: Add retry log
cloudquery/cq-provider-aws pull request #807
Opened 2022-04-28 12:54 UTC by disq

2022-04-28 12:57 UTC, roneli requested changes

2022-04-28 12:57 UTC, roneli commented on client/retry.go
> +	}
extract resource type from error

2022-04-28 13:02 UTC, irmatov commented on client/retry.go
> +func (r *retryer) RetryDelay(attempt int, err error) (time.Duration, error) {
Why not call Standard.RetryDelay here?

2022-04-28 13:04 UTC, disq commented on client/retry.go
> +func (r *retryer) RetryDelay(attempt int, err error) (time.Duration, error) {
Fixed 🙈

2022-04-28 13:04 UTC, disq commented on client/retry.go
> +	}
I tried

2022-05-01 08:31 UTC, roneli approved these changes
LGTM

2022-05-02 14:26 UTC, merged