fix: PK fix for conformance_pack_rule_compliances
cloudquery/cq-provider-aws pull request #809
Opened 2022-04-28 16:10 UTC by spangenberg

The PK was set on the parent but should be on default `cq_id`.
Also the filter for the Details was not applied.

```
cloudquery $ cloudquery fetch aws:config.conformance_packs
An update to CloudQuery core is available: 0.22.10!

Initializing CloudQuery Providers...

Finished provider initialization...

Upgrading CloudQuery providers aws

✓ Upgraded provider aws to latest successfully.

Finished upgrading providers...

Starting provider fetch...

✓ cq-provider-aws@latest fetch complete    3s   Finished Resources: 1/1

Fetch Diagnostics for provider aws:

Resource: config.conformance_packs Type: Database Severity: Error
	Summary: failed to insert to table "aws_config_conformance_pack_rule_compliances": ERROR: duplicate key value violates unique constraint "aws_config_conformance_pack_rule_compliances_pk" (SQLSTATE 23505)
	Detail: duplicate key value violates unique constraint "aws_config_conformance_pack_rule_compliances_pk". [Repeated:36]

Provider fetch complete.

Provider aws fetch summary: ✓ Total Resources fetched: 1	 ⚠️ Warnings: 0	 ❌ Errors: 1
```

With fix:

```
cloudquery $ cloudquery fetch aws:config.conformance_packs
An update to CloudQuery core is available: 0.22.10!

Initializing CloudQuery Providers...

Finished provider initialization...

Upgrading CloudQuery providers aws

✓ Upgraded provider aws to latest successfully.

Finished upgrading providers...

Starting provider fetch...

✓ cq-provider-aws@latest fetch complete    3s   Finished Resources: 1/1

Provider fetch complete.

Provider aws fetch summary: ✓ Total Resources fetched: 1	 ⚠️ Warnings: 0	 ❌ Errors: 0
cloudquery $
```

2022-04-28 20:19 UTC, roneli requested changes
There seems to be migration errors, based on passed experience would also verify after test fixes.
Fetch previous version -> upgrade to this version with data. 
Downgrade back to previous version. 
Run on clean db

2022-04-29 15:41 UTC, spangenberg commented
> There seems to be migration errors, based on passed experience would also verify after test fixes. Fetch previous version -> upgrade to this version with data. Downgrade back to previous version. Run on clean db

It's fixed now, tested everything as well by hand with existing data.

2022-04-29 16:52 UTC, disq approved these changes

2022-05-02 09:26 UTC, roneli requested changes

2022-05-02 09:26 UTC, roneli commented on resources/provider/migrations/timescale/28_v0.11.2.down.sql
> +DROP INDEX "aws_config_conformance_pack_rule_compli_cq_fetch_date_cq_id_idx";
DROP IF EXISTS

2022-05-02 09:26 UTC, roneli commented on resources/provider/migrations/timescale/28_v0.11.2.down.sql
> +  DROP CONSTRAINT aws_config_conformance_pack_rule_compliances_pk,
IF EXISTS

2022-05-02 09:26 UTC, roneli commented on resources/provider/migrations/timescale/28_v0.11.2.down.sql
> +DROP INDEX "aws_config_conformance_pack_rule_compli_cq_fetch_date_cq_id_idx";
same with normal

2022-05-02 12:57 UTC, roneli approved these changes
LGTM

2022-05-04 21:38 UTC, bbernays commented on resources/provider/migrations/postgres/28_v0.11.2.down.sql
> +  ADD CONSTRAINT aws_config_conformance_pack_rule_compliances_pk PRIMARY KEY (conformance_pack_cq_id);
The version needs to be updated to 0.11.3

2022-05-05 15:25 UTC, merged