feat: Add waf/wafv2 logging config
cloudquery/cq-provider-aws pull request #814
Opened 2022-05-02 08:00 UTC by zagronitay

🎉 Thank you for making CloudQuery awesome by submitting a PR 🎉

#### Summary

---

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 🧑‍🎓
- [x] Run `go fmt` to format your code 🖊
- [x] Update or add tests. Learn more about testing [here](https://docs.cloudquery.io/docs/developers/sdk/testing) 🧪
- [x] Update the docs by running `go run ./docs/docs.go` and committing the changes 📃
- [x] If adding a new resource, add [relevant Terraform files](../terraform) in a separate PR 📂
- [x] Ensure the status checks below are successful ✅

2022-05-09 07:35 UTC, roneli approved these changes

2022-05-09 21:18 UTC, bbernays commented
This will require a change to the AWS policy:
https://github.com/cloudquery-policies/aws/search?l=SQL&q=logging_configuration

2022-05-17 12:14 UTC, bbernays approved these changes
LGTM

2022-05-18 12:13 UTC, bbernays approved these changes

2022-05-25 06:46 UTC, yevgenypats requested changes
Looks good. I think child PKs are not needed anymore.

2022-05-25 06:46 UTC, yevgenypats commented on resources/services/waf/rules.go
> +				Options:     schema.TableCreationOptions{PrimaryKeys: []string{"rule_cq_id", "data_id"}},
I think this is unneeded anymore?

2022-05-25 11:08 UTC, bbernays approved these changes

2022-05-27 08:27 UTC, merged