chore: Added Athena tf infrastructure
cloudquery/cq-provider-aws pull request #820
Opened 2022-05-02 18:48 UTC by amanenk

added terraform infrastructure for athena resources

2022-05-02 20:37 UTC, erezrokah requested changes
Looks good @amanenk. Left a small comment.

2022-05-02 20:37 UTC, erezrokah commented on terraform/athena/local/main.tf
> +  prefix = "cq"
```suggestion
  prefix = var.prefix
```

2022-05-03 10:29 UTC, bbernays approved these changes

2022-05-04 06:00 UTC, erezrokah approved these changes

2022-05-04 15:00 UTC, merged