fix: WAFV2 Managed Rules PK
cloudquery/cq-provider-aws pull request #848
Opened 2022-05-04 19:52 UTC by bbernays

🎉 Thank you for making CloudQuery awesome by submitting a PR 🎉

#### Summary

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Update or add tests. Learn more about testing [here](https://docs.cloudquery.io/docs/developers/sdk/testing) 🧪
- [ ] Update the docs by running `go run ./docs/docs.go` and committing the changes 📃
- [ ] If adding a new resource, add [relevant Terraform files](../terraform) in a separate PR 📂
- [ ] Ensure the status checks below are successful ✅

2022-05-04 20:26 UTC, roneli requested changes
Looks good, 1 comment.

2022-05-04 20:26 UTC, roneli commented on resources/provider/migrations/timescale/29_v0.11.3.up.sql
> +-- Resource: wafv2.managed_rule_groups
missing truncate

2022-05-04 20:36 UTC, roneli approved these changes
LGTM, maybe would also truncate on downs to be safe?

2022-05-05 08:34 UTC, disq reviewed
web_acl has child tables, why not `TRUNCATE CASCADE`?

2022-05-05 10:54 UTC, bbernays commented
> web_acl has child tables, why not `TRUNCATE CASCADE`?

Didn't realize that was an option. Have removed the `DELETE` and replaced with `TRUNCATE CASCADE`

2022-05-05 12:13 UTC, merged