fix: Fix region error in `aws_backup_global_settings`
cloudquery/cq-provider-aws pull request #911
Opened 2022-05-17 12:35 UTC by amanenk

🎉 Thank you for making CloudQuery awesome by submitting a PR 🎉

#### Summary

fixes region usage on global resource

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run --new-from-rev main` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests. Learn more about testing [here](https://docs.cloudquery.io/docs/developers/sdk/testing) 🧪
- [ ] Update the docs by running `go run ./docs/docs.go` and committing the changes 📃
- [ ] If adding a new resource, add [relevant Terraform files](../terraform) in a separate PR 📂
- [ ] Ensure the status checks below are successful ✅

2022-05-17 12:46 UTC, bbernays commented
I have an open Ticket with AWS Support to understand why this resource occasionally fails...

2022-05-17 12:46 UTC, disq approved these changes

2022-05-17 13:36 UTC, bbernays requested changes

2022-05-18 18:15 UTC, bbernays commented
Closing because #923 fixes the problem

2022-05-18 18:15 UTC, closed without merging