Add MQ brokers resource
cloudquery/cq-provider-aws pull request #93
Opened 2021-06-11 09:19 UTC by irmatov

Please, take a look

2021-06-11 09:37 UTC, yevgenypats commented
Closes #92

2021-06-15 07:03 UTC, roneli requested changes
Looks good, a few descriptions missing / broken and one missing column in users. I would also add TF integration tests to the MQ. @fdistorted can help you out if needed.

2021-06-15 08:14 UTC, irmatov commented on resources/mq_brokers.go
> +			},
Added

2021-06-15 08:14 UTC, irmatov commented on resources/mq_brokers.go
> +				Description: "Required",
Fixed. Went over all of the descriptions and ensured all are present and correct.

2021-06-15 08:15 UTC, irmatov commented on resources/mq_brokers.go
> +				Description: "Required",
Fixed

2021-06-15 08:15 UTC, irmatov commented on resources/mq_brokers.go
> +				Name:         "aws_mq_broker_configurations",
Fixed

2021-06-15 09:43 UTC, fdistorted reviewed
Everything looks fine. Good job!
Take a look at Ron's suggestions.

2021-06-15 10:56 UTC, irmatov commented on resources/mq_brokers.go
> +					{
Added, along with more fields

2021-06-17 13:09 UTC, roneli approved these changes
Looks great. Just 1 minor comment to check if to delete that file or not and we can merge

2021-06-17 13:09 UTC, roneli commented on docs/tables/cache_behaviour_lambda_function_associations.md
> +
I am pretty sure this file shouldn't exist, if it does (find by table name) than that table should begin with aws_ prefix

2021-06-17 15:43 UTC, roneli approved these changes

2021-06-18 07:31 UTC, merged